spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

azure:
  document-intelligence:
    endpoint: ${AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
    key: ${AZURE_DOCUMENT_INTELLIGENCE_KEY}
    model-id: prebuilt-layout

file:
  upload-dir: ${FILE_UPLOAD_DIR}